### ISSUE TITLE
Data for Angelo and David

### ISSUE THREAD

**Issue by gorgeous1992** [gorgeous1992/gorgeous1992#11]
Hey,

Your data is in the following form

time: 0301/2014 2:00:00 am
columns:
[waveheight wavefrequency depth]
rows: 
awac_8m
awac_6m
awac_5m
(I will figure out the measurement right now)

Zheming

**Comment by gorgeous1992** [comment]
@drobinson6045 @amarney 

The x_coordinates measurements are the following:

awac_8m: xm = 900meters
awac_6m: 550
awac_5m: 450

y_coor is fixed at 950 meters.

Goodluck.
Zheming

**Comment by drobinson6045** [comment]
Awesome.  Thanks Zheming.
