### ISSUE TITLE
How to get coordinates for data awac_8m

### ISSUE THREAD

**Issue by gorgeous1992** [gorgeous1992/gorgeous1992#5]
The data varies on x coordinate but fixed on y coordinate. How can I get the exact value of the fixed y coordinate?

Thanks.

**Comment by thesser1** [comment]
I would set the x coordinate for the 8-m array as 900 and the y coordinate as 950.  I know this is not exact but it is a good enough approximation for how you are using the data.

**Comment by gorgeous1992** [comment]
I will do that. Thank you!
