### ISSUE TITLE
Forecasting Specifying

### ISSUE THREAD

**Issue by grass90** [gorgeous1992/gorgeous1992#8]
Hi, we have a question about forecasting. 
Could you specify how long a period and how big an area you would like to forecast?
For example, would you like to forecast wave height for 3-4 days into the future at one point in the pier where measurements were taken?
Thanks.

**Comment by thesser1** [comment]
I would like a 3-5 day forecast for maximum values in a domain of your
choosing.  It can be a 1-D problem, so the domain would be along a transect
or it could be a regional 2-D problem.
